# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySDKWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for MySDK
  pod 'Toast','4.1.1'

end

target 'MySDKDevDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySDKDevDemo

end

#升级了Toast库的版本后，暂时不需要指定IPHONEOS_DEPLOYMENT_TARGET
#否则会报clang: error: SDK does not contain 'libarclite' at the path错误

post_install do |installer|
   installer.generated_projects.each do |project|
       project.targets.each do |target|
           target.build_configurations.each do |config|
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
           end
       end
   end
end
